// automatically generated by the FlatBuffers compiler, do not modify

package com.yechy.tvassserver.flatbuffers;

public final class TcpMsgType {
  private TcpMsgType() { }
  public static final byte MESSAGE_TYPE_CONNECT_REQUEST = 0;
  public static final byte MESSAGE_TYPE_CONNECT_RESPONSE = 1;
  public static final byte MESSAGE_TYPE_ONKEY_REQUEST = 2;
  public static final byte MESSAGE_TYPE_ONKEY_RESPONSE = 3;
  public static final byte MESSAGE_TYPE_FUNCTION_REQUEST = 4;
  public static final byte MESSAGE_TYPE_FUNCTION_RESPONSE = 5;

  public static final String[] names = { "MESSAGE_TYPE_CONNECT_REQUEST", "MESSAGE_TYPE_CONNECT_RESPONSE", "MESSAGE_TYPE_ONKEY_REQUEST", "MESSAGE_TYPE_ONKEY_RESPONSE", "MESSAGE_TYPE_FUNCTION_REQUEST", "MESSAGE_TYPE_FUNCTION_RESPONSE", };

  public static String name(int e) { return names[e]; }
}

