// automatically generated by the FlatBuffers compiler, do not modify

package com.yechy.tvassserver.flatbuffers;

public final class UdpMsgType {
  private UdpMsgType() { }
  public static final byte MESSAGE_TYPE_FIND_DEVICE_REQUEST = 0;
  public static final byte MESSAGE_TYPE_FIND_DEVICE_RESPONSE = 1;
  public static final byte MESSAGE_TYPE_FIND_DEVICE_CHECK = 2;

  public static final String[] names = { "MESSAGE_TYPE_FIND_DEVICE_REQUEST", "MESSAGE_TYPE_FIND_DEVICE_RESPONSE", "MESSAGE_TYPE_FIND_DEVICE_CHECK", };

  public static String name(int e) { return names[e]; }
}

