// automatically generated by the FlatBuffers compiler, do not modify

package com.example.yechy.tvass.flatbuffers;

public final class KeyStatus {
  private KeyStatus() { }
  public static final byte ActionDown = 0;
  public static final byte ActionUp = 1;

  public static final String[] names = { "ActionDown", "ActionUp", };

  public static String name(int e) { return names[e]; }
}

