// automatically generated by the FlatBuffers compiler, do not modify

package com.example.yechy.tvass.flatbuffers;

public final class SocketMsgType {
  private SocketMsgType() { }
  public static final byte MESSAGE_TYPE_FIND_DEVICE_REQUEST = 0;
  public static final byte MESSAGE_TYPE_FIND_DEVICE_RESPONSE = 1;
  public static final byte MESSAGE_TYPE_FIND_DEVICE_CHECK = 3;

  public static final String[] names = { "MESSAGE_TYPE_FIND_DEVICE_REQUEST", "MESSAGE_TYPE_FIND_DEVICE_RESPONSE", "", "MESSAGE_TYPE_FIND_DEVICE_CHECK", };

  public static String name(int e) { return names[e]; }
}

