// automatically generated by the FlatBuffers compiler, do not modify

package com.example.yechy.tvass.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TcpMessage extends Table {
  public static TcpMessage getRootAsTcpMessage(ByteBuffer _bb) { return getRootAsTcpMessage(_bb, new TcpMessage()); }
  public static TcpMessage getRootAsTcpMessage(ByteBuffer _bb, TcpMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TcpMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte msgType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public short keyCode() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public byte keyAction() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createTcpMessage(FlatBufferBuilder builder,
      byte msgType,
      short keyCode,
      byte keyAction) {
    builder.startObject(3);
    TcpMessage.addKeyCode(builder, keyCode);
    TcpMessage.addKeyAction(builder, keyAction);
    TcpMessage.addMsgType(builder, msgType);
    return TcpMessage.endTcpMessage(builder);
  }

  public static void startTcpMessage(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addMsgType(FlatBufferBuilder builder, byte msgType) { builder.addByte(0, msgType, 0); }
  public static void addKeyCode(FlatBufferBuilder builder, short keyCode) { builder.addShort(1, keyCode, 0); }
  public static void addKeyAction(FlatBufferBuilder builder, byte keyAction) { builder.addByte(2, keyAction, 0); }
  public static int endTcpMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

