// automatically generated by the FlatBuffers compiler, do not modify

package com.example.yechy.tvass.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UdpMessage extends Table {
  public static UdpMessage getRootAsUdpMessage(ByteBuffer _bb) { return getRootAsUdpMessage(_bb, new UdpMessage()); }
  public static UdpMessage getRootAsUdpMessage(ByteBuffer _bb, UdpMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UdpMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte msgType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String ip() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ipAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int port() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createUdpMessage(FlatBufferBuilder builder,
      byte msgType,
      int ipOffset,
      int port,
      int nameOffset) {
    builder.startObject(4);
    UdpMessage.addName(builder, nameOffset);
    UdpMessage.addPort(builder, port);
    UdpMessage.addIp(builder, ipOffset);
    UdpMessage.addMsgType(builder, msgType);
    return UdpMessage.endUdpMessage(builder);
  }

  public static void startUdpMessage(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addMsgType(FlatBufferBuilder builder, byte msgType) { builder.addByte(0, msgType, 0); }
  public static void addIp(FlatBufferBuilder builder, int ipOffset) { builder.addOffset(1, ipOffset, 0); }
  public static void addPort(FlatBufferBuilder builder, int port) { builder.addInt(2, port, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(3, nameOffset, 0); }
  public static int endUdpMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishUdpMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

